BaseURL = "http://www.developersgarage.com/"
Title = "Developers Garage"
LanguageCode = "es"
paginate = 7
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2017"
canonifyurls = true

[params]
  description = "apasionados por la técnologia y la programación"
  cover = "images/cover.jpg"
  
  author = "Jose A2. Luceño"
  authorlocation = "Tarragona, España"
  authorwebsite = "http://www.developersgarage.com/"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "developersgarage"
  twitterName = "developersgarage"
  facebookName = "developersgarage"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"